/**
 * Legacy System Stub
 *
 * Phase 39: This stub replaces the old Google Sheets sync system
 * to prevent server crashes while maintaining backward compatibility.
 *
 * All methods throw appropriate errors indicating the system has been replaced.
 */

const LEGACY_ERROR_MESSAGE = 'This feature has been replaced by the new Google Sheets sync system (Phase 39). Please use the new /api/sheets/* endpoints instead.';

class LegacyStorageStub {
  // Throw error for all methods
  private throwLegacyError(): never {
    throw new Error(LEGACY_ERROR_MESSAGE);
  }

  // Spreadsheet methods
  listSpreadsheets = () => this.throwLegacyError();
  getSpreadsheet = () => this.throwLegacyError();
  getSpreadsheetBySheetId = () => this.throwLegacyError();
  createSpreadsheet = () => this.throwLegacyError();
  deleteSpreadsheet = () => this.throwLegacyError();

  // Worksheet methods
  getAllWorksheets = () => this.throwLegacyError();
  getWorksheets = () => this.throwLegacyError();
  getWorksheet = () => this.throwLegacyError();
  createWorksheet = () => this.throwLegacyError();
  updateWorksheet = () => this.throwLegacyError();
  deleteWorksheet = () => this.throwLegacyError();
  toggleWorksheetSync = () => this.throwLegacyError();
  getWorksheetData = () => this.throwLegacyError();

  // Dashboard methods
  listActiveDashboardTemplates = () => this.throwLegacyError();
  getDashboardTemplate = () => this.throwLegacyError();
  getDashboardTemplateByType = () => this.throwLegacyError();
  listCustomDashboards = () => this.throwLegacyError();
  getCustomDashboard = () => this.throwLegacyError();
  createCustomDashboard = () => this.throwLegacyError();
  updateCustomDashboard = () => this.throwLegacyError();
  deleteCustomDashboard = () => this.throwLegacyError();

  // Calculation rules
  listCalculationRules = () => this.throwLegacyError();
  listActiveCalculationRules = () => this.throwLegacyError();
  getCalculationRule = () => this.throwLegacyError();
  createCalculationRule = () => this.throwLegacyError();
  updateCalculationRule = () => this.throwLegacyError();
  deleteCalculationRule = () => this.throwLegacyError();

  // Data source mapping
  listActiveDataSourceMappings = () => this.throwLegacyError();
  getDataSourceMapping = () => this.throwLegacyError();
  createDataSourceMapping = () => this.throwLegacyError();
  updateDataSourceMapping = () => this.throwLegacyError();
  deleteDataSourceMapping = () => this.throwLegacyError();

  // User methods
  getUser = () => this.throwLegacyError();
  updateUserRole = () => this.throwLegacyError();
  updateUserStatus = () => this.throwLegacyError();
  updateUserProfile = () => this.throwLegacyError();

  // Role methods
  listRoles = () => this.throwLegacyError();
  createRole = () => this.throwLegacyError();
  updateRole = () => this.throwLegacyError();
  deleteRole = () => this.throwLegacyError();

  // Data source relationships
  listDataSourceRelationships = () => this.throwLegacyError();
  getDataSourceRelationship = () => this.throwLegacyError();
  createDataSourceRelationship = () => this.throwLegacyError();
  updateDataSourceRelationship = () => this.throwLegacyError();
  deleteDataSourceRelationship = () => this.throwLegacyError();

  // Purchase records
  listPurchaseRecords = () => this.throwLegacyError();
  getPurchaseRecord = () => this.throwLegacyError();
  getPurchaseRecordsByStudent = () => this.throwLegacyError();
  createPurchaseRecord = () => this.throwLegacyError();
  updatePurchaseRecord = () => this.throwLegacyError();
  deletePurchaseRecord = () => this.throwLegacyError();

  // Consultation records
  listConsultationRecords = () => this.throwLegacyError();
  getConsultationRecord = () => this.throwLegacyError();
  getConsultationRecordsByStudent = () => this.throwLegacyError();
  createConsultationRecord = () => this.throwLegacyError();
  updateConsultationRecord = () => this.throwLegacyError();
  deleteConsultationRecord = () => this.throwLegacyError();

  // Multi-source analytics
  listMultiSourceAnalytics = () => this.throwLegacyError();
  getMultiSourceAnalytic = () => this.throwLegacyError();
  createMultiSourceAnalytic = () => this.throwLegacyError();
  updateMultiSourceAnalytic = () => this.throwLegacyError();
  calculateMultiSourceAnalytic = () => this.throwLegacyError();
  deleteMultiSourceAnalytic = () => this.throwLegacyError();

  // Worksheet analysis
  createWorksheetAnalysis = () => this.throwLegacyError();
  getWorksheetAnalysis = () => this.throwLegacyError();
  listWorksheetAnalyses = () => this.throwLegacyError();
  deleteWorksheetAnalysis = () => this.throwLegacyError();

  // Auto-generated reports
  createAutoGeneratedReport = () => this.throwLegacyError();
  getAutoGeneratedReportsByWorksheet = () => this.throwLegacyError();
  getAutoGeneratedReport = () => this.throwLegacyError();
  updateAutoGeneratedReport = () => this.throwLegacyError();
  deleteAutoGeneratedReport = () => this.throwLegacyError();

  // Sheet mappings
  getSheetMappings = () => this.throwLegacyError();
  getSheetMapping = () => this.throwLegacyError();
  updateSheetMapping = () => this.throwLegacyError();
  resetSheetMapping = () => this.throwLegacyError();

  // Sheet data
  getSheetData = () => this.throwLegacyError();
  getSheetDataCount = () => this.throwLegacyError();
  searchSheetData = () => this.throwLegacyError();
}

class LegacyGoogleSheetsServiceStub {
  private throwLegacyError(): never {
    throw new Error(LEGACY_ERROR_MESSAGE);
  }

  validateSpreadsheet = () => this.throwLegacyError();
  getWorksheets = () => this.throwLegacyError();
  syncWorksheet = () => this.throwLegacyError();
  syncEnabledWorksheets = () => this.throwLegacyError();
  syncSpreadsheet = () => this.throwLegacyError();
}

export const storage = new LegacyStorageStub();
export const googleSheetsService = new LegacyGoogleSheetsServiceStub();
